# Site settings
title: Team USA - World Games 2017 Flying Disc
tag_text: Team USA World Games Flying Disc
description: A barebones guide to following the Team USA in the flying disc competition at World Games 2017 in Wroclaw, Poland.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
