# Site settings
title: Flying Disc Team USA - World Games 2017
tag_text: Flying Disc Team USA
description: A barebones guide to following the Team USA in the flying disc competition at World Games 2017 in Wroclaw, Poland.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
